version: "3.8"

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      macvlan_mode: bridge
      parent: enp0s8
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.130/27" 
          gateway: "192.168.1.1"

services:

  openmeetings:
    container_name: openmeetings
    image: apache/openmeetings:min-6.3.0
    ports:
      - "5443:5443"
    volumes:
      - ./data/omdata:/opt/omdata
    environment:
      - OM_KURENTO_WS_URL=ws://kurento:8888/kurento
      - OM_DB_TYPE=postgresql
      - OM_DB_HOST=postgresql
      - OM_DB_PORT=5432
      - OM_DB_USER=openmeetings
      - OM_DB_PASS=openmeetings
      - OM_DB_NAME=openmeetings
    depends_on:
      - kurento
      - postgresql
    restart: unless-stopped
    networks:
      - macvlan

  kurento:
    container_name: kurento
    image: kurento/kurento-media-server:6
    ports:
      - "8888:8888"
    restart: unless-stopped
    networks:
      - macvlan

  postgresql:
    container_name: postgresql
    image: postgres:15-alpine
    volumes:
      - ~project/data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=openmeetings
      - POSTGRES_PASSWORD=openmeetings
      - POSTGRES_DB=openmeetings
    restart: unless-stopped
    networks:
      - macvlan

